### ISSUE TITLE
Chunky suddenly stops working

### ISSUE THREAD

**Issue by NotRedG** [pop4959/Chunky#103]
Started pregenerating in the end dimension with only 3 mods active, Chunky, Fabric API, and Better End. The pregenerator worked for a little while until I suddenly got this error out of nowhere. No one had logged on, no one changed anything on the server.
[latest.log](https://github.com/pop4959/Chunky/files/6693096/latest.log)

**Comment by pop4959** [comment]
It looks like there is something wrong with the lighting data in the chunk that is being generated. This wouldn't be caused by chunky, so it's got to be something either in vanilla or the better end mod (or you just have a corrupt chunk that can't be loaded).

The best thing to do here is to try restarting the server and continuing from that spot again, and if that doesn't work you might want to delete the broken region and try re-generating it. Worst case it's something with the better end mod and you can't fix it without removing it.

Hope that helps! Join the Discord server if you're still having trouble with anything I mentioned above.
