### ISSUE TITLE
[Feature] detect if there is online player or not

### ISSUE THREAD

**Issue by ElectroBoi** [pop4959/Chunky#104]
hello there I would like to add a suggestion to this plugin, I'm not quite sure if this feature is already implemented, 
but as far as I know this feature does not currently exist,
as the title say it would be nice if chunky can detect if there is any player on the server,
so chunky can run when the server is empty so that it doesn't effect any gameplay.

correct me if this feature is already existed

thanks

**Comment by pop4959** [comment]
Hey! There are currently two other issues open for this, #29 and #81. It's not implemented yet but this is one of the next things I wanted to get around to doing. For right now, it's still possible to pause and continue the task yourself while there are less/no players online. Usually it doesn't give much or any performance hit. Though, for best results, I *always* recommend pre-generating before players join your server (since this has no impact on players and also allows them to join when the map is ready to explore).

Will close this for now since it's more of a duplicate, but feel free to give a 👍 on one of those other 2 issues and keep an eye on them to see when I end up having time to add this. Thanks!
