### ISSUE TITLE
[Question] Copy serverfiles over a pregenerated world with same seed

### ISSUE THREAD

**Issue by Kulturnilpferd** [pop4959/Chunky#114]
I have a little minecraft server with AOF3. Sadly I started the server with people playing on it before I have known that i can pre generate chunks with chunky. On Server Chunky is a bit slow, so I have started chunky with the same seed on my gaming rig to generate the chunks with radius X.
Can I copy the serverfiles that are allready filled with player generated things over the generated world (with same seed) from my gaming rig and then copy these prepared world back on my server?
If  this is working (or possible), can I then start chunky on the server again to generate the chunks missed from the copied server files that are not generated? Or does chunky then generate the whole world again?

**Comment by pop4959** [comment]
Hey glad to hear you're using chunky with AOF :)

It's definitely preferable to pre-generate before players are on your server, but it sounds like you're already aware. Pre-generation can be pretty slow, and especially so if players are playing and loading chunks at the same time. It's also typically even slower when running mod packs, since they add much more to the game than just plain vanilla.

I can't say with 100% certainty that what you are doing will work without any issues, but in theory generating those regions on a separate server with the same seed and copying them back should be fine. Of course, you ***will not*** want to overwrite any existing regions on the server world, since those regions are already partially generated by players, and may contain builds (which are not present in the pre-gen copy).

Re-running over the server after doing that process also sounds like a fine idea. Chunky doesn't re-generate chunks that are already generated, so it would only be filling in any missing ones. Of course, there may not be so many remaining so if you don't care as much you could just let it generate naturally with minimal downsides.

I'd say give it a go, but of course, back up your server beforehand just in case something happens.

If you have further questions, feel free to ask on our [Discord server](https://discord.gg/ZwVJukcNQG), as I'm usually more responsive there than on Github for answering questions.
