### ISSUE TITLE
Changing the center, when process already running

### ISSUE THREAD

**Issue by PetyXbron** [pop4959/Chunky#131]
Hey guys,

can I change the world center when Im already generating?
I would pause the process, then change the center in config, then use `chunky reload` and after all I will use `chunky continue` to continue the process.

I forgot to set the center of world and now it's generating from 0, 0 and I don't want it.

Is that possible to change it, when process is paused?

**Comment by PetyXbron** [comment]
I tried it. It's working!

**Comment by pop4959** [comment]
Glad you figured it out! Just a note - since you moved the center the pre-generation may continue from a different chunk relative to where it was before. Might end up with a couple chunks getting skipped on one side. You can solve this by re-running pre-generation over the area that was missed or just re-doing it in general. Chunks that are already generated will be skipped.
