### ISSUE TITLE
OTG Support

### ISSUE THREAD

**Issue by m-gora** [pop4959/Chunky#142]
Does this plugin support OTG?

Currently I'm pregenerating my multiplayer world locally, as i have much more resources availble than the actual server.
I am afraid that using this plugin to generate chunks during the nighttime to pregenerate in offline / low population time might generate chunks wrongly.

**Comment by pop4959** [comment]
There's normally no difference in generating chunks with or without players online, so any such issue would likely be a bug in the custom generation. Chunky is compatible with 99.9% of plugins, mods, and data packs because what it does is actually quite simple -- it only asks the server to generate the chunks, it does not generate them itself. This means that the actual generation always happens in exactly the same way the server would normally do it (e.g. when players generate chunks manually).

Hopefully that gives you some confidence. As always, I cannot test with every plugin, mod, or data pack, so do your own testing to determine if things are working correctly, and make backups just in case (if using a pre-existing world). If you're still unsure, ask the developer of the custom generation plugin that you are using to see if there are any known issues.
