### ISSUE TITLE
I want the ability to reload already generated chunks.

### ISSUE THREAD

**Issue by goddy516** [pop4959/Chunky#149]
**Affects version**
1.2.153

**Reproduce**

Requires the plug-in "Multiverse-Core" & "Dynmap"
1. Create a world called "TEST" with Multiverse-Core.
2. Start chunk generation. Dynmap will read the chunk generated range.
3. Delete the world called "TEST".
4. Create a world called TEST again.
5. Start chunk generation. If you do the above, chunks will not be generated from the second time onward.

**Observation results**

I think that it is not reflected in Dynmap because it is regarded as a chunk that has already been generated and that chunk is skipped.

**Expected results**

I would like you to add a setting that allows you to switch whether to read the once generated chunk again with "true" or "false".

**Comment by pop4959** [comment]
The new caching system just assumes that the same world name will not be in use for two different worlds during the same ongoing server session. Looks like this could be improved since that actually appears to be possible. For now, you'll have to use an earlier release of chunky or restart the server if you have two worlds sharing the same name.

**Comment by pop4959** [comment]
This should be fixed by 5613f94 since the world is initialized any time it is created or reloaded by Multiverse. Re-creating the world with the same name shouldn't be an issue anymore.
