### ISSUE TITLE
1.18.1 fabric with 1.18 chunky 1.2.153

### ISSUE THREAD

**Issue by HughSparks** [pop4959/Chunky#150]
When running chunky 1.2.153 on a 1.18.1 server it starts off quick then eventually crawls to a halt and crashes.

**Comment by Evigami** [comment]
Can confirm, please fix soon :/

**Comment by pop4959** [comment]
Looks to be working just fine on 1.18.1 for me, for vanilla generation. Since there aren't any further details in this issue I will be closing it, however I recommend looking at the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ) for performance tips, and joining the [Discord](https://discord.gg/ZwVJukcNQG) server for help troubleshooting if you're still having problems.

**Comment by HughSparks** [comment]
[https://spark.lucko.me/P3tQtifgPe](url)
[https://paste-bin.xyz/23233](url)

Sorry, On this server I run: Hydrogen, Sodium, Lithium, Phosphor, FerriteCore, Krypton, and Starlight.

**Comment by HughSparks** [comment]
Chunky Config:
https://paste-bin.xyz/23248

**Comment by HughSparks** [comment]
Spark Heap Summary
https://spark.lucko.me/wdelKfhZd9
