### ISSUE TITLE
Chunky Still crashes on 1.18.1

### ISSUE THREAD

**Issue by HughSparks** [pop4959/Chunky#151]
# #150  Check Latest comment for logs

**Comment by HughSparks** [comment]
Seems to be something in the net.minecraft.world.storage.VersionedChunkStorage.getNbt()
https://spark.lucko.me/P3tQtifgPe?hl=40

**Comment by pop4959** [comment]
Rather than pointing blame at something random, please join the [Discord](https://discord.gg/ZwVJukcNQG) server for help troubleshooting. There are plenty of people there that are happy to help figure out why you might be crashing.

I'd also like to note that the most common cause for a crash currently is due to [MC-245406](https://bugs.mojang.com/browse/MC-245406), a vanilla memory leak impacting old worlds that are upgraded to 1.18. It's much more noticeable when quickly loading lots of chunks, such as with chunky.

If that's not you, there are still quite a number of other reasons why you could be crashing, either due to inadequate server hardware, software bugs, or issues with other plugins / mods.

**Comment by LiskoSlayer63** [comment]
I encountered the same problem that @HughSparks mentioned in #150:
> When running chunky 1.2.153 on a 1.18.1 server it starts off quick then eventually crawls to a halt and crashes.

My server acted just like that, it generated maybe and hour or something and then the speed dropped and finally the server crashed. The only difference was, that I was using Forge instead of Fabric. I solved the problem (at least tweaked things so it didn't crash anymore) and here's how:


1. Changed to [Aikar's flags](https://startmc.sh/)
2. Disabled Dynmap during generation (not sure if this affects or not)
3. Installed [Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
4. Changed RAM allocation from 8G to 24G


With these changes my server generated **a map using [Terralith](https://www.curseforge.com/minecraft/mc-mods/terralith) with 10k block radius in about 24h**, without single a single crash or slowing down. The generation speed sticked around ~20cps at the whole time. *(I tried to calculate it and it seems impossible that it generated the map in that time, can @pop4959 maybe lighten why?)*

**Comment by pop4959** [comment]
Glad to hear your issues crashing were resolved :)

Again, just as a general reminder for anyone looking at this issue in the future, please use the Discord server (linked in the previous post above) for troubleshooting if experiencing crashes. Most crashes during pre-generation are not a bug. It's also quite hard to help with them through GitHub.
