### ISSUE TITLE
[Feature] Scheduled genning start/pause

### ISSUE THREAD

**Issue by Laukage** [pop4959/Chunky#154]
I would be awesome if there was a way to lets say start a chunky at 1 am and schedule it to stop at 7 am.
used for generating chunks at night, which is quite usefull

**Comment by pop4959** [comment]
Thanks for the suggestion! This has been a thought at one point but this is generally a pretty niche ask and I don't really think it belongs directly in Chunky itself as to avoid feature bloat. There are plenty of other plugins that exist (just from a quick google search: [Command Timer](https://www.spigotmc.org/resources/command-timer.24141/), [ConditionalCommands](https://www.spigotmc.org/resources/conditionalcommands.14295/), etc). You can also get creative yourself and schedule it using a data pack or cron job. Basically anything will work since chunky's commands don't require a player to run them.
