### ISSUE TITLE
Generate according to shapes instead of square, so if a task is paused or canceled the world still has the right shape.

### ISSUE THREAD

**Issue by alexanderhorner** [pop4959/Chunky#161]
For example: When I start a new task with the shape circle and radius 5000, and then stop the task before its done, the world will be a square. I think it would be better if no matter when you stop it, the world has the right shape. 

So for the task with radius 5000 and shape circle, when I stop it in the middle of generating the world should roughly be a circle with radius 3000 or something.

**Comment by pop4959** [comment]
The chunks generate in the order defined by the pattern you've selected. You can find further information on Chunky's patterns [here](https://github.com/pop4959/Chunky/wiki/Patterns). By default everything generates concentrically from the center, in a square shape. The final shape will be correct, but no guarantees can be made mid-generation as to how it looks like (e.g. loop will be half filled from one side, whereas concentric will be filled partially from the center).

That being said, mistakes happen and understandably you might cancel partway through. Chunky has a few fixes for this, such as providing the trim command, which will delete the extra chunks that you don't want. For example, you can select the circle shape that you wanted, and trim off the corners.

I have no plans on actually adding a circular pattern, mostly because I'm not even convinced it can be done correctly (at least efficiently). Please feel free to make a pull request if you know how to do it though, because it'd be awesome to add. 😄
