### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by Veseon** [pop4959/Chunky#165]
Hello,

I'm having issues when trying to pre generate chunks, the server runs out of memory and crashes.

Here are some results from a test server I set up on my local machine to reproduce the issue with minimal mods installed.
Heap Summary: https://spark.lucko.me/wcufZ7Nqw6
Profile: https://spark.lucko.me/CVkFAxZaHW

Server is running Fabric 0.12.12 on Minecraft version 1.18.1.
Mods used are Chunky-1.2.170, fabric-api-0.45.0+1.18, spark-fabric#266.

I get the same result regardless of the amount of memory I allocate.

**Comment by pop4959** [comment]
There aren't any known memory leaks in chunky itself, but there are potential memory leaks such as [MC-245406](https://bugs.mojang.com/browse/MC-245406) (if you are upgrading an old world) in vanilla, and often in mods (although seemingly not the case here).

If you want to follow up, please join the [Discord](https://discord.gg/ZwVJukcNQG) server since this is more of a troubleshooting issue. I would also recommend making a heap dump of the server when it is crashes.
