### ISSUE TITLE
Corners option not working properly

### ISSUE THREAD

**Issue by shrx** [pop4959/Chunky#166]
I tried to trim the server chunks with specifying the corner coordinates:

```
> chunky trim world corners -600 -470 540 620
[17:49:08 INFO]: chunky trim - Delete chunks outside selection
```

There is no confirmation message and chunks are not actually deleted even after server restart.

If I trim using the square coordinates it works correctly:

```
> chunky trim world square -30 75 570
[17:56:07 INFO]: [Chunky] Warning: Chunks in world outside of the square region centered at -30, 75 with radius 570 will be permanently deleted. Please make sure you have taken a backup of your server before continuing to avoid potential damage. You will be required to restart your server fully after the task has finished. If you understand and wish to proceed, type '/chunky confirm'.
```

Using Chunky jar version 1.2.164 on a 1.18.1 world.

**Comment by pop4959** [comment]
The reason you are getting an error is because "corners" is not a valid argument for trim.

The syntax for [trim](https://github.com/pop4959/Chunky/wiki/Commands#trim) currently is `chunky trim [world] [shape] [<centerX> <centerZ>] [radius] [radius]`. As you can see it only accepts a center and radius parameters (which could be 2 for rectangles).

That said, you probably would want to use corners to select a rectangle. The idiomatic way of doing this would be:
```
chunky corners <x1> <z1> <x2> <z2>
chunky trim [world]
```

Of course, no chunks are actually deleted until you confirm the action. This is for safety since it gives you a chance to confirm that what you selected is accurate, and that you've had a chance to backup your world.

Take a look at [trimming chunks](https://github.com/pop4959/Chunky/wiki/Trimming-chunks) on the wiki for more information about the nuances of how trim functions. Notably you should not have the chunks loaded on your server or load them after running trim, until you restart your server.

If you have any other questions about using chunky, please feel free to join our [Discord](https://discord.gg/ZwVJukcNQG) server.

**Comment by shrx** [comment]
Hi, thanks for your response. It was not clear in the wiki that corners are not supported.

**Comment by pop4959** [comment]
> Hi, thanks for your response. It was not clear in the wiki that corners are not supported.

Corners *are* supported, but it is a separate command, not a shape as you were trying to use it. 😄

**Comment by pop4959** [comment]
Just to clarify again, these commands are what you would want based on your example:
```
chunky corners <x1> <z1> <x2> <z2>
chunky trim [world]
```

The first command selects by corners, and then the second command trims that selection for the world specified (or the current one if `[world]` is left out).
