### ISSUE TITLE
No passive mobs in pregenerated chunks

### ISSUE THREAD

**Issue by ScorchedPsyche** [pop4959/Chunky#168]
Hello,

I pre-generated 8000 block radius before the start of my season for 1.18.1. However, as we are playing it, there are no passive mobs around.

Does chunky generates passive mobs? Could this be a bug?

Thanks in advance!

**Comment by pop4959** [comment]
Not a bug, this is almost always a configuration issue of some sort (a plugin preventing mob spawning, disabled mob spawning in server.properties, game rules, or setting a world border too small before pre-generating since mobs will not spawn past the world border).

You'll probably want to re-generate the map (and check that you've got the mobs properly spawned this time). It may be a good idea to use a fresh server for the pre-gen itself, so that you're 100% sure that it is free of anything that would be causing issues such as the examples I gave above.
