### ISSUE TITLE
Feature request: forcefully tick paper watchdog

### ISSUE THREAD

**Issue by Hex27** [pop4959/Chunky#169]
https://github.com/PaperMC/Paper/issues/7306

**Comment by pop4959** [comment]
I don't see any reason to add this in Chunky itself, as `max-tick-time` already exists in server.properties which can be used to effectively disable the watchdog. The only reason why you should *ever* see a watchdog crash normally is if the server is actually in a position where it *should*, as during normal pre-generation the server will not crash. This could be because you have a bad hosting provider that's shoving the entire server onto 1 thread (Minecraft is not single threaded despite what people would like to believe) or using a world gen plugin/mod that is not very well optimized.

As for that last part, I am aware that you are the TerraformGenerator dev and I am not at all claiming that your plugin specifically is poorly optimized... but I do think this is an issue worth investigating. I spoke to electroniccat briefly on the Paper Discord about how useful ticking the watchdog is and his response was "The question is really 'why is the server stalling[?]'", which I generally agree with. It doesn't happen for no reason. Other plugins like Terra work just fine, so I'm not convinced that this is an inherent problem.

So the 3 solutions I see you have right now is to either identify what's causing hang-ups in your plugin, continue telling users to disable watchdog when generating chunks, or try ticking the watchdog yourself when it's taking a long time to generate, so that the server doesn't stall and crash.

I've sent you a friend request on Discord in case you want to follow up on this with more details, or just to keep in touch.
