### ISSUE TITLE
Memory Leak on 1.19

### ISSUE THREAD

**Issue by MagnusRevang** [pop4959/Chunky#189]
There is definitively a memory leak on 1.19. I'm running a 10000, 10000, -10000, -10000 generation and with 4GB RAM on the server it starts lagging on memory problems and ultimately crashes at around 40%... I have to restart the server and continue after that, seems to go ok, but it will be interesting to see if there is any chunk errors from it.

**Comment by pop4959** [comment]
There doesn't seem to be enough information in this issue to "definitely" say that there is a memory leak. Keep in mind that generally, chunky just generates chunks and memory issues or leaks can be caused by a number of other factors. Unless you are absolutely certain and have evidence to back that, it's nothing I can look into further.

I recommend joining the [Discord server](https://discord.gg/ZwVJukcNQG) for basic troubleshooting first, and if we can verify this we can re-open the issue.

Keep in mind that I'm about to hop off for tonight so you likely won't see a response till morning sometime.
