### ISSUE TITLE
CSV pattern missing from Wiki

### ISSUE THREAD

**Issue by RandomGgames** [pop4959/Chunky#198]
There is a pattern labeled CSV which is not explained under the patterns page.

A nice touch would also be to add an image for all options, not just 2 of 4.

**Comment by pop4959** [comment]
Thanks, I have updated the documentation to reflect the new pattern.

Keep in mind that for all intents and purposes, concentric and spiral are identical, due to the nature of spanning from the center outward.

Logically they are very different (and if you look at the code you can see they are), but it is largely an implementation detail, and in fact (funny enough) they are 1:1 the same currently in terms of chunk visitation order.

The default is concentric purely because it is marginally more efficient than the spiral pattern. You will not notice the difference between the two outside of benchmarking.

I did not make the images (they are provided thanks to @donvi-bz), although it does not really make much sense to add either concentric (due to being functionally identical) nor CSV (since this is a user defined order).

I hope that answers all of your questions. If you'd like to chat more about this, or potentially help with the docs (as I generally have limited time to make improvements myself), join the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG).
