### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by Trivernis** [pop4959/Chunky#2]
Please add a license to this repository so I know under which terms I can use it.

**Comment by Chew** [comment]
@Trivernis It's a Spigot plugin so GPL 3

**Comment by Trivernis** [comment]
It's not that spigot plugins all have the same license afaik

**Comment by Chew** [comment]
Exactly, and that license is GPLv3

**Comment by Trivernis** [comment]
Now you're confusing me...

**Comment by Chew** [comment]
All spigot plugins have to use gplv3

**Comment by Trivernis** [comment]
Wait, where's that written? I've seen plugins use Apache 2.0 and stuff or are they just violating the license rule?

**Comment by Chew** [comment]
it's written in the license, they technically either have to use gplv3 or not use bukkit api I believe is how it works

**Comment by Trivernis** [comment]
Oh, yeah, seems like you're right

**Comment by Trivernis** [comment]
Still it's interesting that spigot itself offers you to sell your plugin which isn't really compatible with gpl.
So yeah, technically those plugins are all licensed GPLv3 but if someone uses something different the spigot devs apparently are also fine with it (it even seems like md_5 didn't know about the GPLv3 thing)

**Comment by Chew** [comment]
Oh no, you're allowed to sell your plugin. You just need to either open source it or give the source to people on request.
Bukkit itself is GPLv3 see https://github.com/Bukkit/Bukkit/commit/6255d1794c4995b65dbd3db8b857a7d356266c5e
CraftBukkit, Spigot, Paper all use Bukkit, so they're all GPLv3 as well.

**Comment by Trivernis** [comment]
Yeah, you're allowed to sell it, I just meant that its difficult since you also have to freely distribute the source code.

**Comment by pop4959** [comment]
@Trivernis Apologies for the late response, as I saw this issue a few days ago but forgot to reply to it. Chew is correct in that all Bukkit plugins must be GPL compliant, although I believe they are allowed to have a more permissive license as well. This is because all plugins must extend JavaPlugin which make them a "derivative work". I am not a lawyer however, so take that as you will. Spigot doesn't seem to be too strict on enforcing licenses however, and have their own rules regarding resources posted on their platform.

I plan to put an explicit license statement on the plugin soon, it just hasn't been a priority. Things have just been moving more quickly than anticipated. All code in this repository can be considered open source and provided in good faith.

I'm also aware that you are the author of Chunkmaster, so I'm guessing you are looking to implement something similar to Chunky's chunk generation. Chunky is a simple plugin, however the generation is handled in a very different way. I'm not sure how feasible it is for you to do something similar in your plugin, but of course you are welcome to try.

**Comment by Trivernis** [comment]
Thanks for the response. You're right that I wanted to try using the concept of generation that chunky uses for chunkmaster. As you guessed it would not work since your plugin works in a very different way. I think we can pretty much agreement that Chunky beats Chunkmaster in speed.

**Comment by pop4959** [comment]
That may be the case, although I think the use case is very different for each plugin. Chunkmaster has options to control the generation speed to make it friendly to live servers with players online, and so it runs more stably on servers. On the other hand, Chunky tries to just get it done as quickly as possible. So it isn't really a competition of speed, but rather what server owners prefer to run on their server.
