### ISSUE TITLE
{BUG} Trim corners not working as intended on 1.19.2

### ISSUE THREAD

**Issue by ShiftingKill** [pop4959/Chunky#208]
I am having issues trimming a world on 1.19.2. I've been able to trim 5 of my worlds so far, but this one world is just particularly tricky yet chunky has no errors. Not all the terrain has been trimmed, in fact it has some glitchy areas that got partially trimmed.

**Comment by pop4959** [comment]
Have you checked the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ#trim-isnt-working)? The most common problem people encounter with trim is that it can't delete actively loaded chunks on the server. I'm assuming this is most likely your issue.

Going to close this for now since there isn't enough evidence to suggest a bug, however if you have reason to believe that it is we can re-open the issue here. For further help troubleshooting, visit the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG).
