### ISSUE TITLE
Pause generation progress automatically when players join

### ISSUE THREAD

**Issue by zekroTJA** [pop4959/Chunky#227]
It would be awesome if you could enable an "auto-pause" mode which automatically pauses a running task when a player joins the server and automatically resumes the task when no players are on the server anymore.

**Comment by pop4959** [comment]
Thanks for the suggestion! This is already possible but not built-in. You can download [ChunkyPause](https://github.com/pop4959/ChunkyPause/releases) or any other add-on using [Chunky's API](https://github.com/pop4959/Chunky/wiki/Developer-API) for managing your generation.

I'd like to note that pausing based on player counts is generally not recommended. It's best to pre-generate before you launch your map with players. Even if that's not possible for some reason (for example expanding a map live) there is usually no harm in just letting it run while players are online. Chunk loading may be a bit slower in general but there shouldn't be any other major impact, as since Minecraft 1.13 chunk generation is not done on the main server thread.

There are probably a few edge cases where this is actually a useful feature, but as far as I'm concerned it's pretty much limited to running on extremely low end hardware, in which case the performance benefit of pre-generating in the first place is limited as you will suffer in other areas as well.

Hopefully that makes sense as to why I'm not all too keen on this feature (and anything adjacent related to pausing based on X). The idea with the API was that servers that require the extra flexibility will be able to do whatever they need. If you want to discuss this more or have questions about the API please join our [Discord](https://discord.gg/ZwVJukcNQG) server, but as with previous issues covering this topic I will be closing for now.

**Comment by zekroTJA** [comment]
Okay, thank you very much for the hint. Actually, on our server which is a relatively cheap 6c/t VPS the TPS falls down to almost 5-6tps when generating chunks for some reason. But we also discovered performance issues in general when more than 5-6 people are playing simultaneously on the server.

**Comment by pop4959** [comment]
Hm yeah that definitely sounds like more of a hardware issue. Glad I was able to point in the right direction!

**Comment by TerdyTheTerd** [comment]
*Hoping this doesn't re-open this ticket* 
Just wanted to add, I find this feature very helpful during the initial server creation phase, where 1-2 admins get on the server for a few hours to build stuff, but I don't trust them to ensure they pause and restart the pregen every time they get on/leave. Let's me run the pregen without worry and let's my staff get on when they need to work on stuff, and since the pregen needs to run for over a week I dont want to dedicate an entire week to purely generating:)

**Comment by pop4959** [comment]
> _Hoping this doesn't re-open this ticket_ Just wanted to add, I find this feature very helpful during the initial server creation phase, where 1-2 admins get on the server for a few hours to build stuff, but I don't trust them to ensure they pause and restart the pregen every time they get on/leave. Let's me run the pregen without worry and let's my staff get on when they need to work on stuff, and since the pregen needs to run for over a week I dont want to dedicate an entire week to purely generating:)

Not sure if you read the original response I gave this issue, but having 1-2 players online building while pre-generating should have zero impact on your server's performance. If you're still worried then use the add-on plugin that I linked. Also if it's taking you >1 week to pre-generate you're probably generating too much. Take a look at [tgb's world size calculator](https://onlinemo.de/world) for how big that's going to be. Most servers generate about 5-10k which will take a few hours to a day to complete.

If you still have questions or any concerns about your pre-gen please join the #chunky channel on the [Discord server](https://discord.gg/ZwVJukcNQG). Going to lock this conversation now to avoid further unwanted emails to the person who made this issue.
