### ISSUE TITLE
Command "chunky" not found

### ISSUE THREAD

**Issue by KyotoGuru** [pop4959/Chunky#229]
Hello. I ran into a problem: when I enter the "chunky" command, an error appears that such a command was not found. I play single player. 1.19.2 The mod is installed in the Mod-menu. The error appears when using any version of the mod. Sorry for my English, I'm using a translator.

**Comment by pop4959** [comment]
In a single player world you need to enable cheats in your world (which you can easily do within the "Open to LAN" menu) in order to use chunky. Once you have done so you should gain access to the command. If you are still struggling with this visit the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG).

**Comment by KyotoGuru** [comment]
Thanks a lot, it worked

**Comment by pop4959** [comment]
Awesome, glad to hear. Have fun using Chunky!
