### ISSUE TITLE
Trim command not deleting any chunks

### ISSUE THREAD

**Issue by rm20killer** [pop4959/Chunky#230]
Server Version: paper-1.19.2-112
Plugin Version: 1.3.38
**Issue:**
When trying to trim no chunks are being deleted even with noone on the server.
There are chunks that been generated past 2100.
Even tried restarting the server after and before the command and no changes to the region files where done.
```
/chunky:chunky trim world_the_end square 0 0 2100
/chunky confirm
[Chunky] Warning: Chunks in world_the_end outside of the square region centered at 0, 0 with radius 2100 will be permanently deleted. Please make sure you have taken a backup of your server before continuing to avoid potential damage. You will be required to restart your server fully after the task has finished. If you understand and wish to proceed, type '/chunky confirm'.
[Chunky] Task started in world_the_end for the square region centered at 0, 0 with radius 2100.
[Chunky] Deleted 0 chunks from world_the_end in 0.001 seconds.
 ```

**Comment by pop4959** [comment]
Have you read the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ)? There is section explaining why it might seem like trim isn't working. Specifically, chunks that are loaded by the server (in memory) cannot be trimmed properly as they will be saved again upon shutdown. Often this is caused by visiting them in-game before/while running trim.

The workaround is to not load these chunks until after performing trim and also restarting the server. If you still see the regions after the server has shut down, it implies that the server has re-saved these regions after being trimmed.

If you're still struggling with this, please join the #chunky channel on our [Discord server](https://discord.gg/ZwVJukcNQG).
