### ISSUE TITLE
External Alerts Integration for long duration generation commands

### ISSUE THREAD

**Issue by makcuber** [pop4959/Chunky#239]
Since one of Chunky's primary use cases is to generate a large area of a world which can take many hours, I think adding some sort of external alerts integration would be very useful. I personally use Pushover for my server alerts as it works well and is very affordable, but the integration would ideally be able to support any external alerts system for things like generation start, stop, pause, and complete events. 

I found an example that does something like this in very old plugin someone made that tries to do this (https://github.com/jobukkit/MinecraftPush) so it seems that such an integration would be possible to do, but I don't know whether it makes more sense to have this functionality as a separate plugin that Chunky integrates with or to have it as part of Chunky itself. 

This is more a "nice to have" feature, so I don't expect much to come of it, but I figured it'd be worth throwing the idea out there in case anyone wants to take a crack at it.

**Comment by pop4959** [comment]
That sounds very sensible, however integration for various notification systems is not something I am particularly keen on or interested in maintaining in Chunky myself. I understand that there is a want for these things though which is why a [Developer API](https://github.com/pop4959/Chunky/wiki/Developer-API) was recently added to the plugin to allow people to customize around it to their liking.

The current API is simple but it should be more than enough to implement simple monitoring for tasks. In fact, someone's already implemented it for [Discord](https://github.com/Fhoz/ChunkyDiscord). I would imagine Pushover is similar. I'm more than happy to lend advice in implementing the integration from the plugin side, or assist in finding a solution if you run into any trouble making it work.
