### ISSUE TITLE
suggestion: separate file for saved data from config

### ISSUE THREAD

**Issue by MicleBrick** [pop4959/Chunky#24]

**Comment by pop4959** [comment]
I believe I've fixed the issues we discussed since when this issue was created. Saving is now done sync on shutdown, which makes it a lot more reliable and consistent for a larger number of worlds. There is also a reload command, so tasks can be edited when paused, and then continued without needing to restart the server.

I don't think I will be moving the tasks to a separate file for now, since there doesn't seem to be any added benefits to doing so at the moment. If it makes sense in the future I will do it.
