### ISSUE TITLE
No-Players Pregeneration

### ISSUE THREAD

**Issue by RikuTheKiller** [pop4959/Chunky#240]
Please add a config option that makes chunk pregeneration automatically start when the player count reaches 0 and stop whenever it goes above that. (For smaller servers.)

**Comment by pop4959** [comment]
If you use the issue search feature you should find multiple posts where I've answered this already, but in short: I do not see a strong reason for this to be included in Chunky, and pre-generating with players online should have little impact on your performance, especially if there are only a few players online.

If you feel like you really need it you can use an existing addon plugin to achieve this functionality, such as [ChunkyPause](https://github.com/pop4959/ChunkyPause) (which does the player pausing you are talking about), or write your own using the [API](https://github.com/pop4959/Chunky/wiki/Developer-API) to pause and manage tasks in any way you like.

If you need any help with any of the above please use our [Support Discord](https://discord.gg/ZwVJukcNQG) and visit the chunky channel there. You should receive responses much more quickly than here on Github.

**Comment by RikuTheKiller** [comment]
"should have little impact on your performance" Yeah, sure.
If you consider leaking several gigabytes of memory and having the server run several seconds behind to the point where you can't even play the game to be a "little impact on your performance".

On another note, I'd recommend posting a link to ChunkyPause's releases page on the main page of the mod. You can't blame people for asking stuff like this if you literally have a solution yet don't make it public knowledge.

**Comment by pop4959** [comment]
I saw you came by the Discord; wanted to respond there but saw you already left.

In regards to the performance impact you are seeing on Forge - this is probably almost entirely caused by the mods you have doing things to hang the main thread on world gen. If you can identify any that are causing these issues for you, I would heavily recommend reporting this behavior to the authors of those mods, as this can be considered a bug. World gen is not done on the main server thread, so any mods stalling it significantly during world gen is just not acceptable IMO.

With that said, glad you found the data pack for pausing! If you had mentioned you were on Forge, I would have linked to that instead of the plugin example.

Wish you happy pre-genning!

**Comment by pop4959** [comment]
Just as a follow up for anyone who might come across this post in the future: Riku and I troubleshooted a bit on Discord and as it turns out, the issue was just memory allocation.

If you're experiencing crashes, before turning to alternatives, make sure your memory allocation for the server is set correctly, with a few gigabytes of overhead for the container / system.
