### ISSUE TITLE
Progress Bar Stuck at Top of Screen

### ISSUE THREAD

**Issue by AquaLawng** [pop4959/Chunky#242]
I run a Minecraft server for my friends and me. I added chunky to the server mod folder to preload chunks where most of the servers activity will be. I then did the following:

1. Started server, with newly added Chunky, and logged on so I could decide on a radius
2. /chunky center 600 -3500
3. /chunky radius 1000
4. /chunky start

A progress bar appeared at the showing the progress of the generation. 
At around 81%, and 7 minutes left, I logged off the server as I had some IRL to do and didn't want my player dying when I was gone. The server console showed the chunk generation progress. I later logged on, and the progress was stuck at the top of the screen, even though the generation was complete.

![Screenshot 2023-02-20 095736](https://user-images.githubusercontent.com/61892317/220140201-46578e94-854c-48b8-aec5-fb97748e9607.png)

**Comment by pop4959** [comment]
I think this might be two bugs; if you can submit a different issue for the second one that would be appreciated. 👍 

The progress bar issue has been reported a couple of times in Discord, but I've been unable to reproduce it on my end. I originally tried fixing this in 91c9d9d33506dc667697fb3b204d3664064ad9da which made the issue less bad, but it still happens. Your observation about it happening after stuff finishing and rejoining the server might be it though, I'll have to test that.

As a temporary fix, use the [bossbar remove command](https://minecraft.fandom.com/wiki/Commands/bossbar) to remove the boss bar. This will work because the boss bars Chunky uses are registered as normal vanilla boss bars. They're just managed along with task progress.

As for the other issue, again please submit another issue if you can and since this feels like more something we would want to troubleshoot, I highly recommend joining the chunky support channel in our [Discord server](https://discord.gg/ZwVJukcNQG) so I can help figure this out. I've never seen this issue occur.

**Comment by pop4959** [comment]
Unable to produce as described, having spent more time looking into this. I have a bunch that this only occurs on old versions of Chunky, as I haven't had any reports of this in a while with newer versions. If I'm wrong please let me know, but there is not enough information here to continue further.
