### ISSUE TITLE
Can't choose a world for pregeneration

### ISSUE THREAD

**Issue by Jarkness** [pop4959/Chunky#246]
I'm trying to pregen nether for my modded server.
I'm using Magma server 1.18.2.
The command I'm using:

`chunky world world_nether`

The output I'm getting:

`chunky world <world> - Set the world target`

Also, I tried several different world names, such as the_nether, world_the_nether and minecraft:the_nether.
The End pregeneration does not work either.
Autocompletion shows nothing but "world".

`chunky world world` works as expected.

**Comment by pop4959** [comment]
For Forge based servers please use [Chunky Forge](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge). This kind of issue has been reported before on our Discord and is caused by bugs in Hybrid server software. If you have any further questions please join the chunky support channel on our [Discord](https://discord.gg/ZwVJukcNQG).
