### ISSUE TITLE
Unkown Registry Key

### ISSUE THREAD

**Issue by pjt0720** [pop4959/Chunky#25]
Hello again,

In my console when running Chunky I am now getting a error that says "Unknown Registry Key: minecraft:normal_tree"

Don't know if this is a Minecraft thing again or the plugin!

PasteBin:
https://pastebin.com/EDQJXcet

Thanks,
pjt0720

**Comment by pop4959** [comment]
Yeah this is another server message (specifically DFU - Mojang's "DataFixerUpper").

"DFU spam" is a common issue for servers upgrading from older versions of Minecraft to 1.16.

You can tell this isn't a message from Chunky because it comes from the "Paper Async Chunk Task Thread" which is handled by code in Paper and Vanilla. This is indirectly related because Chunky asks the server to load (and generate) chunks, and so any errors that may pop up will be related to whatever gets encountered while it's doing that.

Feel free to report such issues over at [PaperMC/Paper](https://github.com/PaperMC/Paper) and they might be able to look into it. I haven't seen your particular error yet anywhere.

**Comment by pjt0720** [comment]
lol, gotta love Mojang!

**Comment by pop4959** [comment]
@pjt0720 BTW also 77k hours ETA seems a bit long, not sure what radius you have but it's probably too big to feasibly generate or store on disk.
