### ISSUE TITLE
Very low tps on generation 

### ISSUE THREAD

**Issue by masmc05** [pop4959/Chunky#252]
https://spark.lucko.me/b2Qa2f7dto

using a dev build, but that's too much, maybe that's because of chunk tickets being added before the chunk is generated

**Comment by masmc05** [comment]
so i think it's because of https://github.com/pop4959/Chunky/issues/237 implemented in https://github.com/pop4959/Chunky/blob/f912195a26dff944dd35a0fe45457fe2e05e069f/bukkit/src/main/java/org/popcraft/chunky/platform/BukkitWorld.java#L56

**Comment by pop4959** [comment]
Thanks for the spark link, that's very helpful.

This has nothing to do with the random line of code you linked (which isn't even run by default without adding a startup flag).

The problem is this:

![image](https://user-images.githubusercontent.com/17698576/224512349-59cc1b33-1d93-4ae5-a1f8-7ac0960bab05.png)

No wonder you're having issues when getChunk keeps calling itself recursively.

I'm going to assume that this is caused by one of the many plugins you have. Try without plugins first, on Paper, and see if you have the same issues. If you do still, join chunky support channel in the [Discord server](https://discord.gg/ZwVJukcNQG). I would be surprised if this is a bug with Chunky, but if it is we'll figure that out after troubleshooting more.

**Comment by pop4959** [comment]
Discussed on Discord, but turns out this actually was a bug in one way. Tickets were being placed from off the main thread when using the ticking load duration system property, and before generation could occur, seemingly causing some of the weird issues here.

That said TPS drops are not a bug, this is somewhat expected when ticking these chunks for a duration, for which the server then performs post process generation on these chunks.

Fixed by 9ee34d398373796b58263694b02c0006bcc8e63e.
