### ISSUE TITLE
[Feature Request] Config option to auto pause if TPS drops too low

### ISSUE THREAD

**Issue by GNUGradyn** [pop4959/Chunky#265]
Would be nice if you could set the plugin to automatically pause itself if the TPS dips below a certain threshold to allow more headroom for the server to run

**Comment by pop4959** [comment]
Hi, unfortunately as discussed in previous issues there are no plans on adding anything like that directly into Chunky. Generally speaking, chunk generation will not affect your TPS either, since TPS measures the main server thread and chunk generation is done on the world gen threads.

However this is still possible via an integration if you use the [Chunky API](https://github.com/pop4959/Chunky/wiki/Developer-API).

If you need help troubleshooting performance issues also consider joining the chunky support channel in our [Discord server](https://discord.gg/ZwVJukcNQG).
