### ISSUE TITLE
It is NOT working

### ISSUE THREAD

**Issue by QueenUlyana** [pop4959/Chunky#269]
I created a world border using commands: 
chunky radius 1000
chunky border add
As a result, I can in survival mode, and my friends can pass through the border. Also, there is a BAG, when approaching the boundary of the world, many items visually disappear when playing from 1st person. This is bullshit!

https://github.com/pop4959/Chunky/assets/83131824/f7f582c6-8158-4ac0-b19d-b078d9438df1

**Comment by QueenUlyana** [comment]
Visual bugs come from the border, after I removed the border, the objects began to display normally.

**Comment by pop4959** [comment]
Hi, for troubleshooting, please join the [Discord server](https://discord.gg/ZwVJukcNQG). Github is mostly used for feature requests and bug reports.

My guess is that you have border bypass configured, either because you are OP or because you have the bypass permission. I would check that first to make sure it isn't the issue.
