### ISSUE TITLE
Chunky not shutting down properly

### ISSUE THREAD

**Issue by tlrichar** [pop4959/Chunky#28]
Getting this error from paper-182.java server on shutdown

[11:28:14 ERROR]: Nag author: 'pop4959' of 'Chunky' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.

**Comment by pop4959** [comment]
You received that error because you did not pause the tasks before shutting down the server, and Chunky was attempting to save them. This process is very quick normally but in your case it took longer than usual and printed that error. This can also occur more frequently on low end systems. It is not a bug.

TLDR; you should probably pause your tasks properly and not rely on shutdown to save them.

**Comment by tlrichar** [comment]
I could not pause the task because chunky was causing the server to crash.

**Comment by tlrichar** [comment]
Yeah, I had to stop using WorldBorder on 1.16.2 because it was causing chunks to be skipped. Chunky does, we just need fill frequency of some sort :)

**Comment by pop4959** [comment]
Fair enough. It may take some time still for me to get around to implementing a limiter, but it is fairly high on to to-do list at this point. Originally there weren't any plans for this, which is why it doesn't exist yet. The idea was that the automatic rate of generation would always match that which the server is able to support, however it seems that is not always the case. If you don't mind, please add me on Discord and I'll let you know when I have something for you to test.

**Comment by pop4959** [comment]
Fixed the original issue in 1576da7e0ec9fc93609bcf848c9ff5917b57e70e.

You should no longer get the nag warning, and task saving is now done sync on shutdown, which means that it should never be the case that tasks fail to save by the time the server stops, even on low-end systems.
