### ISSUE TITLE
Allow for chunk skipping in generation options

### ISSUE THREAD

**Issue by Kamorzy** [pop4959/Chunky#298]
If it had an option for generating every other chunk, for instance, it could cut the processing time and file size in half, yet might still be enough pre-generation that newly generated regions don't lag for many users. Or perhaps we could do the full chunk generation close to the origin, then only do half generation very far away where its less likely to be visited at all.

Ideally, users could set how many chunks to generate until it skips the next one: 1 (every other), 2 (every 2/3), 3 (every 3/4).

I think a lot of users would naturally prefer to optimize their resources with a feature like that.  For me, its critical. My disk space is very very limited.

**Comment by pop4959** [comment]
This doesn't do what you think it does; chunks in Minecraft are generated along with their neighbors (up to a required status). So generating "every other chunk" in say, a checkerboard pattern has neither the properties of significantly reducing the disk space or time required to generate. You end up effectively with all of the chunks, with every other generated to full, and the others ready to be decorated, but otherwise also full.

That said, chunky already supports fully customizing the generation pattern by providing a file to declare exactly what chunks you want generated in what order. You can read about it a bit more on the [patterns](https://github.com/pop4959/Chunky/wiki/Patterns) page on the wiki. If you need any help with this, please visit the [Discord server](https://discord.gg/ZwVJukcNQG).

Generally I would recommend instead of trying to rely on specific tricks like this, try to optimize your server, your plugins / mods (especially those with a large impact to world gen, some can easily double the generation time due to inefficiencies), and try not to bite off more than you can chew in terms of generation size. If the ETA is several weeks, it's probably too large. Instead aim for generating as much as you can do in a day, as that usually ends up being sufficient.
