### ISSUE TITLE
Make /chunky command available when in singleplayer

### ISSUE THREAD

**Issue by steve-the-player** [pop4959/Chunky#307]
Some commands, both vanilla and modded, can work when cheats are disabled in a world. Usually, when I first start a world I'll run `/chunky start` to help mitigate lag, but this is currently disabled. It feels weird that a utility like preloading the world isn't globally available. I also don't like having to do the open to LAN trick. (I've actually got a mod that disables LAN cheats)

**Comment by pop4959** [comment]
Not a bug - so going to re-label as an enhancement instead. The issue here is that chunky is a server mod and the commands that are available through it can be considered dangerous, so they require OP and are not granted by default.

The unfortunate thing here is that this means for singleplayer the commands are not available and the player cannot acquire OP / cheats easily without temporarily opening to LAN.

Someone on Discord recently suggested making the command accessible in *singleplayer only*, but still requiring OP when the game is in multiplayer mode. I've decided that this is appropriate and plan on integrating this change into an upcoming version of chunky - so look forward to it! Hopefully this will make singleplayer use of chunky a bit easier.

**Comment by pop4959** [comment]
Added in 0f65dbc19bdda3163e5de944c7082da688eb812c.
