### ISSUE TITLE
API Task doesnt start instant on a newly created world

### ISSUE THREAD

**Issue by Knerio** [pop4959/Chunky#311]
Server Setup:
  - Paper #388
  - Pterodactly
  
I am currently trying to create a world and then preload a little, but the problem is that the task that I create via the API, which I start one tick after the onEnable, is not started properly for 2-2.5 minutes

```
[16:47:17 INFO]: Timings Reset //here the task is already started

[16:49:34 INFO]: [Chunky] Task running for world_571a4754-0120-4165-8f9f-fb26e26d7293. Processed: 5 chunks (0.46%), ETA: 0:01:08, Rate: 15.8 cps, Current: -1, 3  //here it starts
```

The weird thing is, that if i start a task via the Console, everything works.
I also tried to use Bukkit#dispatchCommand to execute a task, but the same problem occured there.
I also tried to use a longer delay, but that didnt work too

The Code i use is this:

api.startTask(customWorldName, "circle" / "square" (i tried both), 0, 0, 250, 250, "concentric" / "spiral" (i tried both));

**Comment by pop4959** [comment]
Discussing through Discord; this appears to not be an issue with the API but rather something intrinsic to the chunk system or the hardware this is being run on. Also happens when using the built-in commands which is a big red flag. Going to close this as "not an issue" but as such continuing to troubleshoot through Discord support.

**Comment by pop4959** [comment]
Increasing `worker-threads` as mentioned on the FAQ basically "solved" this for anyone wondering.
