### ISSUE TITLE
[Server Hang] Server hangs shortly after running chunky

### ISSUE THREAD

**Issue by Camawama** [pop4959/Chunky#331]
Minecraft: 1.20.1
Forge: 47.2.17
Chunky: 1.3.136

Logs: 
[2024-04-14-2.log](https://github.com/pop4959/Chunky/files/14970062/2024-04-14-2.log)

You might see "Too many Physics objects in Physics Queue". This is NOT the issue. Valkyrien Skies always spams the logs when it isn't receiving updates. The game crashes very quickly after running chunky but was running perfectly fine before! The only performance mods installed are ModernFix and ServerCore.

**Comment by pop4959** [comment]
I don't see anything here that suggests that this is a bug with chunky. Generally server stalling is caused by other factors, such as mods you have installed. For help with troubleshooting these issues please join the support channel on our [Discord server](https://discord.gg/ZwVJukcNQG).

If you still believe this is a bug, please let me know and provide further information & replication steps to re-open this issue.

**Comment by Camawama** [comment]
I can fly around generating chunks just fine...but a few seconds after starting a chunky process, the server just hangs and times everyone out. It's only happening when using chunky. I'm sure it's a conflict with another mod on my modpack.

**Comment by pop4959** [comment]
These sorts of problems tend to not be a conflict *with* chunky, but rather flaws in other plugins and mods that present themselves only when generating a large volume of chunks (automating via pre-gen) or a generation condition that happens rarely (so it's unlikely you would reproduce it by simply flying around).

We only provide troubleshooting support over [Discord](https://discord.gg/ZwVJukcNQG) so please join there if you would like additional help.
