### ISSUE TITLE
[Suggestion] Configurable ETA calculations

### ISSUE THREAD

**Issue by johnyuki** [pop4959/Chunky#34]
A nice little, if not insignificant, feature would be to let us control how the average cps. It looks at the last 10s by default when calculating the ETA, it'd be nice if we could change that to look at the last 5s, or 60s, etc.

**Comment by pop4959** [comment]
Thanks again for the suggestion, but I don't think I'm going to add this because it really seem to make much of a difference when you change the sampling interval for the ETA. It averages out to about the same. What I might do is add an overall estimate which considers the entire running duration of the task, as that's probably the only reason why anyone would want to change the sampling interval anyway. It would be best to calculate that separately though since it can be done much more efficiently.
