### ISSUE TITLE
Multiple Chunk Errors while generating world

### ISSUE THREAD

**Issue by YodaDude2011** [pop4959/Chunky#351]
While starting a Chunky job, after a period of time my server will shut down. After restarting the server and continuing the job via "chunky continue", the server will crash again with the same errors: "Chunk system error at chunk", " Exception generating new chunk", "Requested chunk unavailable during world generation", along with several errors.

This server is running in Paper 1.21 Experimental build #38, and using Chunky 1.4.10. 

[latest.log](https://github.com/user-attachments/files/16034657/latest.log)
[2024-06-28-3.log](https://github.com/user-attachments/files/16034658/2024-06-28-3.log)

Here are log files from server start, and then restarting the server and doing "chunky continue".

Please Advise

**Comment by pop4959** [comment]
It may be an issue with Paper or one of your plugins or data packs. Try without any plugins or data packs first, and if this still happens, then report it to Paper, as 1.21 has a lot of changes around the chunk system. I don't expect that any of these changes should break chunky however since it only uses API.

If you still have any issues or have any questions, please feel free to join the [Discord server](https://discord.gg/ZwVJukcNQG) for help.
