### ISSUE TITLE
Confirming memory leak when paused.

### ISSUE THREAD

**Issue by Barerock** [pop4959/Chunky#353]
Since I can't contribute to the other thread after being told that confirming factors are irrelevant to the thread, I will note my findings here: I just followed the steps and confirmed that Chunky will indeed run out of memory if at any point the game is paused during a preload job.

I don't exactly know how preload works, but my guess with how it interacts with Distant Horizons is that it simulates visiting that area? Perhaps pausing eliminates the game's ability to allocate memory because the client is inactive while the server is not, and thus the areas can't be "allocated" to? My thought process is hard to explain in English. I'm new to pregenerating worlds, so I have limited technical knowledge of its cogs.

**Comment by pop4959** [comment]
Thanks, sorry, I thought you were trying to get help for a different freezing issue.

Regardless, the issue is already confirmed, and it is generally unhelpful to bump such issues if you have nothing further to add.

Please join the Discord server to ask any questions you have and we will be happy to help you there.
