### ISSUE TITLE
[feature request] make `chunky help` specify that the radius is in blocks

### ISSUE THREAD

**Issue by SpoogLord** [pop4959/Chunky#356]
basically title. 
For me i found this mod through DeceasedCraft and assumed the radius was in chunks, but when it finished and the chunks generated wasnt what i expected i did the math and it was about what you would expect from that radius divided by 16, i think just for clarity the command description in chunky help should specify that the radius is in blocks

**Comment by SpoogLord** [comment]
also (and this should probably be a separate request but i dont wanna blow up your issues tab) maybe some sort of 'pause when players are logged on'? would be nice for "pre"-generating massive world sizes while a few people are playing on the server, basically im thinking 'oh hey i want a 200 gig world, preload x amount of chunks.. wait what do you mean its gonna take 3 weeks? i wanna play on the server while its doing this but dont want to experience the performance hit and dont wanna manually pause and unpause generation'

**Comment by pop4959** [comment]
It's in blocks, as every other Minecraft command (unless specifically mentioned). This is well documented on the plugin page and wiki through examples. It's also not mentioned in the command as you *can* in fact pre-generate both by blocks (by default) or chunks (see [here](https://github.com/pop4959/Chunky/wiki/Commands#radius) for an example). As such, I don't really generally plan to change this just to cater to the assumptions of one group. From my experience, I see it go both ways, people either assume it's blocks, or they assume it's chunks - in both cases the issue is they did not read the documentation. 😄

As for the second question, you can safely pre-generate without server lag most of the time. Such a feature is not included in chunky, as it would lead to the incorrect assumption that something like this is necessary. If you are not able to pre-generate with players online, you are most likely running on hardware that is not sufficiently powerful enough to host a Minecraft server, or you have other mods/plugins causing lag while generating. I would suggest joining the [Discord support server](https://discord.gg/ZwVJukcNQG) if you have any such issues to troubleshoot.

That said, there are mods and plugins that allow you to customize the behavior of chunky tasks via the API. If you have very specific needs, that is also a valid option.

**Comment by SpoogLord** [comment]
>  you can safely pre-generate without server lag most of the time. Such a feature is not included in chunky, as it would lead to the incorrect assumption that something like this is necessary.

tbh i didnt test it but the pack i mentioned suggested pre-generating chunks before players join to prevent lag, so i assumed it would be an issue. 

Otherwise you do have a point about reading documentation, but in cases like mine where the mod just comes with a pack with no direct link to proper explanations its just a convenience feature. Ultimately tho not my mod not my decision

**Comment by pop4959** [comment]
> tbh i didnt test it but the pack i mentioned suggested pre-generating chunks before players join to prevent lag, so i assumed it would be an issue.
> 
> Otherwise you do have a point about reading documentation, but in cases like mine where the mod just comes with a pack with no direct link to proper explanations its just a convenience feature. Ultimately tho not my mod not my decision

Pre-generating beforehand is a suggestion. Pre-1.13 it was required, because world gen was done on the main thread, which tanked performance pretty badly. But these days it really isn't that much of an issue unless you have bad mods installed.

Unfortunately I don't control what mod packs include chunky or how they document pre-generating, all I can do is provide the docs on the mod page and wiki. Still appreciate the suggestion though!

Hope you're enjoying chunky, and of course, if you have any other questions or just want to discuss more feel free to drop by the Discord server.
