### ISSUE TITLE
Ability to skip confirming

### ISSUE THREAD

**Issue by H4ckerxx44** [pop4959/Chunky#369]
I mostly use chunky on my private servers and I found myself being a little annoyed by `chunky cancel` and `chunky confirm` every time.

I would be a cool config option to `skip confirm` or something similar to that which just lets me `chunky cancel` without confirming.

Let me know what you think.

**Comment by pop4959** [comment]
Is there a reason why you are cancelling so often? Doesn't feel like that should happen a lot (or at all).

The cancellation message is to ensure that users don't accidentally delete the task without realizing and then need to start over again. It is also possible to stop without cancelling using the pause command.

**Comment by H4ckerxx44** [comment]
Not really something that the "general user" would encounter.

When running the server and my minecraft on my local machine, I have occurences like this (cps being near 0):
![grafik](https://github.com/user-attachments/assets/e090f136-13df-439e-90b0-67ac27ef6680)

with them also sometimes just being stuck indefinitely.
Nothing I "want" to report as a bug cause I got lots of mods installed and that behaviour is, I am 95 % sure, just caused by my CPU being occupied with different things and all.

**Comment by pop4959** [comment]
Yeah I think spot on, for the reasons you mentioned I don't think it makes a whole lot of sense to add this. Take a look at the FAQ and join the Discord server if you need help troubleshooting the performance issues. Also I would recommend making use of pause, as that appears to be more relevant to your issue regardless (you can pause, stop the server, and restart, if you are still forced to work around the issue with your mods).

**Comment by pop4959** [comment]
> Oh that is totally fair, by system property, do you mean a java system property (looking at the source code, it seems like it) `-Dchunky.trim.skip_confirm_for_console_command_sender` (name pending)
> 
> And thank you for even considering this!

Please read [here](https://github.com/pop4959/Chunky/wiki/System-Properties) for more details. And no worries, things change. The use case you are describing is different from the original owner of this issue and it makes sense to me.

Please keep in mind, this is a closed issue and generally it is a better idea to open a new issue for a feature request rather than "bumping" or "necro-posting" on an old issue, as anyone subscribed to this old issue will now be receiving emails. If you can, please open a new feature request for this to continue discussing, you may still tag / link to this issue as related.
