### ISSUE TITLE
Refuses to render chunks from the BetterEnd mod.

### ISSUE THREAD

**Issue by spzt101** [pop4959/Chunky#382]
As the title says. It works with other mods. With BetterEnd, after rendering the main island and the empty space around it, it just halts. Completely.

**Comment by pop4959** [comment]
Chunky does not modify how generation works at all. It just reports the progress. If it is halted, this is most likely a problem with one of your mods. Common troubleshooting includes removing mods and seeing if the issue still occurs. If you believe the issue is with Better end, I would recommend removing this mod and seeing if it's still an issue. If it is, you probably want to report this to them and not here (as we can't fix broken generation).

If you need any further help troubleshooting or have any other questions please join the chunky Discord server and we'll be happy to help.

**Comment by spzt101** [comment]
I'll report it to them. It doesn't prevent chunk generation from other dimensions other than the end dimension, and when removed it works fine. Thanks for the quick response!

**Comment by pop4959** [comment]
No problem. I understand that it's frustrating, so best of luck getting that fixed!
