### ISSUE TITLE
Running out of memory when leaving Chunky running

### ISSUE THREAD

**Issue by Noxillio** [pop4959/Chunky#54]
Chunky uses little to no additional memory when I start but several hours later the server stops (PebbleHost shuts down servers automatically when they reach memory limit) due to being OOM. Is there any remedy to this or can it be looked into?

**Comment by pop4959** [comment]
I have gotten numerous complaints from PebbleHost users about running Chunky on their servers.

Chunky does not control how much memory it uses, as this is determined by the server's usage itself as it requires for chunk generation. As a result, there is not much I can do personally to fix this kind of problem.

As far as what you can do (re-interpreted from the [FAQ](https://github.com/pop4959/Chunky/wiki/FAQ#how-can-i-make-chunks-generate-faster)):

- Ensure that your server has at least 2 threads available. 4 is recommended for best performance. Some hosts, such as PebbleHost, offer plans for only 1 thread. Not only does this struggle in general on modern versions of MineCraft, but it also starves any tasks that would normally run on their own threads. This can heavily impact java garbage collection, which is responsible for freeing up memory on your server.
- Have enough memory available. 4GB+ is recommended for running chunk generation.
- Using Paper is recommended, however if you are really having problems, you could try running on Spigot (at least just for pre-gen). This will run chunk generation **slower** because it is less efficient, however this might help if Paper is running too quickly for your server to keep up with garbage collection.
- Ask your host (PebbleHost) to use Aikar's flags for your container, **with sufficient overhead**. This means that if you have purchased an 8GB plan, you might ask them to set your flags to 7GB instead. The 1GB of overhead will ensure that your container does not run above their limit of 8GB and get killed by the daemon.

The last point above may be the most helpful to you if PebbleHost is actually killing your server automatically due to memory limits as you're saying. If all else fails, your last option is to find a new host.

Hope that helps! If you have any further questions feel free to let me know or hop on the [Discord server](https://discord.gg/PHpuzZS) and visit the #chunky channel. 😃
