### ISSUE TITLE
[Feature] Upgrade chunks in an existing world

### ISSUE THREAD

**Issue by TixTux** [pop4959/Chunky#67]

**Comment by TechnicJelle** [comment]
This feature could be immensely useful for people wanting to use BlueMap, or other mapping mods/plugins that load the world files directly from disk, instead of through server APIs. Often those world files are a little broken, until the server loads them, because only then do those chunks get fixed.
Having a reliable, cross-platform solution for cases like these that we can recommend would be very useful. Currently, we can only recommend a CleanLight plugin for Bukkit-based server softwares, but there doesn't seem to be anything that can fix these issues on Forge or Fabric servers. If Chunky were to get this feature, that would be very, very helpful! ^-^

**Comment by pop4959** [comment]
Possible now with 9947f37a26965985fbb3d102ecdf2456e4047e25, only took just over 3 years to get around to this! And it wasn't even really that difficult, except for the fact that we needed to include an NBT library to get there. 😄
