### ISSUE TITLE
Server doesn't start with LuckPerms installed

### ISSUE THREAD

**Issue by Nidre** [pop4959/Chunky#72]
Fabric server 1.16.5 don`t start with Chunky.
[2021-02-07-5.log](https://github.com/pop4959/Chunky/files/5937945/2021-02-07-5.log)

**Comment by pop4959** [comment]
It's working for me, and I don't see anything in your log that indicates an error with Chunky.

Is this a new problem? Did it work with previous versions? More information would be appreciated.

**Comment by Nidre** [comment]
With 1.2.8 server don`t start too
[2021-02-07-6.log](https://github.com/pop4959/Chunky/files/5938109/2021-02-07-6.log)

**Comment by pop4959** [comment]
Closing this because I'm fairly certain at this point that it's a LuckPerms issue. I've heard from other people now that this happens commonly with other mods too. For now, a workaround is just to run Chunky without LuckPerms, and then add LuckPerms only after you are done pre-generating.

**Comment by pop4959** [comment]
@Nidre I spoke with Luck and he managed to figure out what the problem was. Should be fixed in the latest version of LuckPerms and Chunky, as it happened to be a bug on both sides. If anyone continues to have this issue, I recommend updating either to the latest version.

You can find the latest version of LuckPerms [here](https://luckperms.net/download) and Chunky [here](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/).
