### ISSUE TITLE
[Feature Request] Chunky CLI version

### ISSUE THREAD

**Issue by hamcoremusic** [pop4959/Chunky#76]
I think it would be super cool that *if possible* we can get a CLI (Command Line Interface) version of this plugin so we are not required to run a Spigot server alongside the pre-generation.

This idea comes from BlueMap where the developer made a CLI version so you can generate the map without needing a server running on the PC, making the generation a little faster all together.

I don't know if it's really possible to do, but I think it would benefit a lot for people migrating to 1.17 as they could pre-generate a world on vanilla instead of waiting for Spigot.

**Comment by scarifyFX** [comment]
poggers

**Comment by NotGeri** [comment]
No clue how that'd work but pretty pogger idea indeed.

**Comment by scarifyFX** [comment]
> No clue how that'd work but pretty pogger idea indeed.

Wow yes this idea is poggers indeed with proof of being poogers.
PROOF: https://www.youtube.com/watch?v=QTT5iHCHSn0

**Comment by hamcoremusic** [comment]
I'm never posting a GitHub link in Bloom's server ever again

**Comment by pop4959** [comment]
This idea has actually come up already (not as an issue, but as general discussion) and unfortunately I've deemed it's not really possible because it would require the CLI version to include a copy of Mojang's code for world generation which first of all would be very illegal to distribute, and second of all would be difficult to rip apart properly out of the server code. I also have doubts that there would be a very large performance improvement. BlueMap gets away with this because they don't need to generate the chunks; they only need to read the chunks from the region files which is a well documented format and has non-Mojang implementations by third parties.

Fortunately your second comment can be addressed by the fact that we have a Fabric mod version of this project which can be run on a Fabric server. The Fabric project updates to each snapshot on the day it comes out, and I've actually already run Chunky on 21w06a and it worked perfectly. A 1.17 version of the Fabric version will be released when 1.17 is released. Since you can run Fabric without any mods and it is equivalent to Vanilla, you should be able to create the worlds and then transfer them over to Spigot when it updates.

**Comment by hamcoremusic** [comment]
Thanks for the insight! I gathered it wouldn't be possible without breaking EULA. Seeing that Chunky has a Fabric version will make this perfect for 1.17 with their speedy updates!

**Comment by hamcoremusic** [comment]
Actually, since this is on topic. Where do we get the Fabric version? Is it the same .jar?

**Comment by pop4959** [comment]
I meant to include it in the last response but you can find release versions on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator) or snapshots on [CodeMC](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/).

**Comment by EuanM199** [comment]
Press F to pay respect
