### ISSUE TITLE
Name collision with Chunky (Minecraft rendering)

### ISSUE THREAD

**Issue by jackjt8** [pop4959/Chunky#77]
A small unfortunate issue with naming this project Chunky is that Chunky in the context of Minecraft already exists and has done since 2010, or Dec 23, 2012 on Github, see [Chunky](https://github.com/chunky-dev/chunky). While I understand that these projects are used for different purposes, that of world rendering and server chunk generation, the fact these projects have the same name and are related to Minecraft has already lead to some confusion.

I would be happy to clarify the ambiguity on Chunky (rendering), and related projects where possible, providing links back to this repo similar to how vcstools handled a similar issue (https://github.com/vcstools/vcstools/issues/135). Just wanted to hear if you had any ideas as I suspect that this project is only going to grow in popularity.

**Comment by pop4959** [comment]
Thanks for reaching out. It's definitely an unfortunate naming choice, considering I had no clue about the existence of your project prior to creating this one. Could have been a bit more original I suppose, as I came up with Chunky in about 2 seconds, and the only thing I checked when publishing was that the name wasn't already taken on Spigot's resource section.

I don't think there will be any issues with the projects being named similarly, as they are in very different circles in the Minecraft community as you've already mentioned, so it is difficult for users to get the two confused.

Renaming the project is not something I'm planning currently, so please feel free to clarify any ambiguity on your end as you deem necessary. I'll definitely be linking to your project if I ever see any inquiries about it. Although, so far I've had none, but two the other way (looking for my project and finding yours), so I suspect the naming hurts this project more all-in-all.

**Comment by jackjt8** [comment]
Which is completely understandable and we cannot expect you to search around or anything. We have just had the odd person confuse the two discords so far.. so we are just reaching out now to give you a heads up as we do some touch-ups.

One positive outlook from this is that we often do need to tell people to use a tool or plugin such as this to fix up server worlds. The vanilla server launch option `--forceUpgrade` and the optimise world option in single player often skip chunks which can lead to some issues. At least we can easily work in a few mentions to this project and send you some traffic.

**Comment by pop4959** [comment]
Ah OK, I can see how this is happening now. Some people probably found their way onto your site and since you have your Discord server emphasized there, they ended up joining and asking about the wrong project. I suppose creating a command macro to explain the difference between the two projects would be a quick fix for that.

It's interesting that you bring up `--forceUpgrade` since the behavior of this Chunky to upgrade chunks is more of an implementation detail. The goal is to only generate what hasn't already been generated, so we actually try to skip chunks where possible. It's just that DFU is usually run in the process of loading the chunk data enough to check it's current state. Regardless, you can safely rely on this behavior for now as that detail is unlikely to change, and if it does I'll try to find some other way to allow upgrading chunks again since it's useful.

That said, I definitely appreciate the openness to cross exposure between the two projects. That's beyond what I would have expected with this sort of exchange. Hopefully the extra clarification on both sides will reduce the confusion for users to a minimum, and if not, I can later again re-consider this project's name (although it would be quite a hassle at this point).

Lastly, feel free to add me on Discord if you'd like to keep in touch. My tag is pop4959#1781. Keep in mind that I do receive a lot of unsolicited friend requests, so if your tag is dissimilar to your Github username please notify me beforehand.
