### ISSUE TITLE
[Question] Pregenerating World Usage More Ram?

### ISSUE THREAD

**Issue by aril3721** [pop4959/Chunky#78]
Hello I Owner From Small Server With 20 - 40 players. I Have 2 Question if i run pregeneration with 20 - 40 players on a server Usage More Ram?. How Much Time To Need 10k Block Border To Pregeneration? Can This Run On 7GB Ram?

Spec
7GB Ram
Yatopia 1.16.5

**Comment by pop4959** [comment]
It's not recommended to run pre-generation while players are online, because it can cause server lag (especially with player chunk loading) while the world is being generated. 7GB RAM should be enough, and the time it takes will vary depending on the speed and capability of your CPU. See the wiki [here](https://github.com/pop4959/Chunky/wiki/FAQ#can-i-make-chunks-generate-faster) for more details.
