### ISSUE TITLE
chunk pregenerating transitioning across saves

### ISSUE THREAD

**Issue by SpinnyBoiii** [pop4959/Chunky#93]
i was testing the mod(was a bit hard without completion status but theres already issue and response to that) and noticed that, when i deleted a world i had a pregen task going and made a new world, it would say theres already a pregen task going when i was starting a new one.
is this intentional so people dont have to bother using the command for every save?

**Comment by pop4959** [comment]
Chunky currently only allows running one task per world, largely due to limitations in Minecraft's world generation. This means it's not possible to run two tasks for the same world simultaneously. I'm not entirely sure if I understood your problem correctly, but it sounds like you may be running into that.

The task is saved (in Bukkit) to `/plugins/Chunky/config.yml`, which stores it by world name. If you deleted another world and created a new one by the same name, most likely you'll need to ignore the warning and start a new task anyways. The warning is intended to prevent people from accidentally restarting their task instead of continuing it (which did happen quite frequently).

**Comment by SpinnyBoiii** [comment]
ah alright, that was indeed the case then since im a lazy bastard that doesnt give worlds different names xD
